# Global configuration options. The `queue_ahead` and `tz` options can also be set on each task.
queue_name: "default" # The Sidekiq queue name used by SimpleScheduler::FutureJob
tz: "America/Chicago"

# Runs once every day
simple_task:
  class: "DailyWorker"
  every: "1.day"
