Level.create(start: "tip", target:"tap", path: ["tip", "tap"], limit: 2)
Level.create(start: "listen", target: "silent", path: ["listen", "silent"], limit: 2)
Level.create(start: "mad", target:"hat", path: ["mad", "had", "hat"], limit: 3)
Level.create(start: "this", target:"that", path: ["this", "thin", "than", "that"], limit:4)
Level.create(start: "lead", target:"gold", path: ["lead", "load", "goad", "gold"])
Level.create(start: "hood", target:"wink", path: ["hood", "hook", "honk", "wonk", "wink"])
Level.create(start: "word", target:"link", path: ["word", "work", "wonk", "wink", "link"])
Level.create(start: "hide", target:"seek", path: ["hide", "hied", "heed", "seed", "seek"])
Level.create(start: "play", target:"work", path: ["play", "pray", "prey", "pyre", "pore", "pork", "work"])
Level.create(start: "apple", target:"zebra", path: ["apple", "ample", "amble", "blame", "blaze", "braze", "zebra"])
